### ISSUE TITLE
SPIKE: Implementation Options for Facial / Gestural Tracking 

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#123]
As a PM, I know that turning on facial / gestural recognition in our software is a complicated feature. I also believe that capturing that data would allow us to develop more sophisticated analytics, that would add value to our product. 

Our current implementation is client-side, and requires so much processing that it results in a poor UX. We chose to implement it client side because 1) it is inline with our privacy position to NOT record and store user data in a way that is personally identifiable, and 2) sending that data to a server for non-client-side processing, requires effectively adding another "peer" to the call in order to capture and send the data, which is also resource intensive. 

I am hoping that the technology may have evolved since we last tried this, and I would like to understand if there are any different implementation options that we did not have before. 

** Story Acceptance Criteria **
A written document that contains the following: 
- [ ] A general summary of the current state of the technology and the likelihood that we can implement a solution with WebRTC technology and our current architecture. 
- [ ] An explanation about if its possible to capture and store F/G data that remains in line with our privacy policy to not store identifiable content about a user. 
- [ ] An explanation of if there are client-side processing methods that would not result in poor UX, and rough cost of implementation.
- [ ] An explanation of if there are server-side processing methods that would not result in poor UX, and rough cost of implementation.
- [ ] An explanation of if it's possible to do a partial implementation to capture just the top 1 -3 gestures that would be most valuable for Riff.  
- [ ] What open-source F/G libraries are available and what they capabilities they provide.
- [ ] A recommendation on what the best path forward is.

**Comment by jaedoucette** [comment]
@adonahue This looks pretty concrete to me. 

The OpenFace library's pre-processing steps could be a good starting point. https://cmusatyalab.github.io/openface/

The main tools are dlib (http://blog.dlib.net/2014/02/dlib-186-released-make-your-own-object.html), which can estimate the pose a person is in in a picture, and OpenCV's affine transformations (https://docs.opencv.org/2.4/doc/tutorials/imgproc/imgtrans/warp_affine/warp_affine.html) which let you slide a picture around. Combined, these let you convert an image that contains a face into one where the eyes and the mouth are always in the same place.

**Comment by jaedoucette** [comment]
The first step here might be just to see what's out there and available and come back and report to the team about what is already supported in javascript. Then, we can decide if any of the already implemented / supported libraries do things that we think are sufficiently interesting.

The criteria for deciding whether something might be a good candidate are:
1) Does something interesting (in the list of potential facial-gestural things we can detect)
2) Has good performance -- i.e. is demonstrated to be lightweight enough to be integrable into our client without bogging down the experience for the user
3) Isn't old, poorly written, or otherwise suspect as code and therefore unreliable (which is obviously a judgment call on the part of the developer)

So, this spike has two parts (and we'll probably just make a new one):
1) Discovery
2) Viability -- where viability is determining how to implement a library we find that's interesting
