### ISSUE TITLE
Fetch Google Docs to display based on properties of the name of a Riff Video Chat Room.

### ISSUE THREAD

**Issue by jaedoucette** [rifflearning/zenhub-platform-project#151]
NOTE: this story has been discussed and estimated but is back in as a candidate this sprint b/c the estimate may have changed now that @jordanreedie has done other work related to this. 

## Describe the ideal solution or feature request
This feature is a followup on Zenhub #131, which adds the capability to display a hard-coded Googledoc alongside a Riff Video chat in the new layout proposed in Zenhub #130.

This feature will modify the feature developed in #131 so that rather than displaying a hard-coded URL.

When a user creates a new Riff Video Chat room, they want to be able to access a document associated with the name of the room, so that each meeting can have its own "scratch space" separate from the spaces of other meetings.

When a new room is created, the system should search within a specific, hard-coded, path within Riff's Google drive (e.g. ExperimentDirectory/) that has previously been set world-readable by a Riff employee. All files within this prefix should be world-readable and world-editable. The system should determine the fileid or sharing URL of the document with the same name as the newly created Riff video chat room. The name searched for should match the exact text of the name displayed to users of the Riff meeting (which may differ from the name of the meeting as stored in the riff-server database, since repeated meetings in the same room have numbers appended to make their names unique). 

If this document does not exist somewhere within the hard-coded path, or the documents permissions do not allow it to be loaded without authentication, then an informative, human-readable, error message should be displayed, and room creation should fail (i.e. the user will not be able to join the video call). 

If a unique document with correct permissions exists, then the document should be displayed in the portion of the screen reserved for displaying Google Docs per Zenhub #131.

Once the room has been created and the document has been loaded, all future attempts to join the same room should result in the user's display automatically loading the doc that has already been associated with this room name, so that all the users can see and edit the same document, per Zenhub #131.

If a meeting ends, and then much later, a new meeting is started with the same room name, then the same google doc should be loaded (i.e. the contents of the doc associated with a meeting room name will persist across meetings with the same room name).

Acceptance Criteria:

- [ ] A user can create a google doc in Riff's google drive under a directory specified by the implementer of this feature, set permissions so than anyone can edit the doc they have created, put content of their choosing in the doc, and set the title of the doc to a (unique) string of their choice. When they open a new Riff video chat call with a room name that matches the title of the doc they created, the document they created is displayed, with exactly the content they put in earlier, adjacent to the video feeds for the Riff meeting (in a configuration exactly like Zenhub #131).
- [ ] When additional users join a Riff video call that already contains at least one user, the document that is displayed to them is the document that matches the name of the room, and is the same document that that the other users can see and edit.
- [ ] All users in a video call continue to be able to edit the loaded google doc, exactly as in Zenhub #131.
- [ ] Layout remains exactly the same as specified in Zenhub #130.
- [ ] If a user leaves the meeting (including the meeting creator), and then returns later to the same room name, they can still view and edit the same google doc, even if they return much later, and even if everyone else left the room since then.
- [ ] If a user enters a room name without someone first creating a corresponding document in Riff's google drive under the developer-specified path, then an informative error message is displayed when the user attempts to create the room, and room creation fails.
- [ ] If a user creates two or more documents with identical names within Riff's google drive, and then attempts to create a room with the same name, then room creation fails and an informative error message is displayed to the user.
- [ ] Using the name stored in the riff-server Mongo database, a Riff staff person can easily re-load the document associated with a specific meeting after the meeting has ended simply by opening the link in their browser.

## How does this tie into our current product?
As with other designs in this chain, it is less important that solutions be optimized for inclusion in customer-facing Riff products, or that they be easy to maintain, than that they be stable and provide the required feature set quickly.

A variation on this feature might be included in a future version of Riff. This work could be viewed as a spike solution for a future build of a more robust customer facing feature.

## Who asked for this?
John, as part of the grant experiment.

**Comment by jaedoucette** [comment]
We think this doesn't need to be re-estimated, Jordan doesn't think he's learned a ton about this yet.
