### ISSUE TITLE
(tracking card) Network Graph - Functional Enhancements

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#176]
This story is a placeholder to collect functional enhancements for the network Graph feature, so they can be reviewed and prioritized. Checked issues have another card written for the work.

- [x] Nodes drift past the boundaries of the graph.
- [x] Graph nodes do not match the Riff color pallet, or story specifications.
----
- [ ] Deleted Posts do not get subtracted from the counts.
- [ ] Replies in DMs count as DMs and not the subtype “Reply”. This was as requested in the feature, but I think it makes more sense to track them as threaded replies, since that suggests a more focused type of response. 
- [ ] Posting as the only member of a channel shouldn’t count (it does currently). 
----
- [ ] Name-based mentions probably don’t work. Need to prioritize and test. 
- [ ] Also, mentions for “@here”
-----
- [x] Riffbot probably should not display in the graph or count towards course activity.
----
- [x] We should count video.
