### ISSUE TITLE
Deploy new features to http://demo.riffplatform.com/

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#247]
As the CEO, I want our demo site to reflect all our new features, so that we are able to show and test the value of our product. 

As a PM, I want users to create "regular" Riff accounts on our demo site, so that we do not need to maintain two sign-up processes (our and via Qualtrics), and so that users do not need to know the name of a document/room to use the demo site. 

** Acceptance Criteria **
This story is to complete the following:

- [ ] Create new prototype branch for rapid development and deployment to Riff demo site. 
- [ ] The original, visual updates of the Riff dashboard for the demo site (#190).
- [ ] The switch to amChart metrics and the addition of interruption and affirmation metrics (#245).
- [ ] Vertical tiling on the screen share feature, without document functionality (#235). 
- [ ] The Google doc functionality (#220, #236).
- [ ] Putting sign-up, log in, and profile functionality back in.
- [ ] Removing text chat functionality.
- [ ] Deploy to http://demo.riffplatform.com/

**Comment by adonahue** [comment]
Per conversation w. @mlippert :

Probably missing step in here to create a new "prototype" branch from staging, into which the GT features above can get cherry-picked. 

Also an open question about the timing for this story - should it be after the GT features are better vetted and deployed to GT staging.

**Comment by brecriffs** [comment]
It will be easier to estimate feasibility for the dashboard related items, once they are vetted. But this seems pretty easy, once we find a flow for organising prototypal work in a branch that we can cherrypick from.
