### ISSUE TITLE
Data Pipeline Design, Blend and Anonymize Data

### ISSUE THREAD

**Issue by adonahue** [rifflearning/zenhub-platform-project#66]
This story is part of our initial data pipeline that will allow us to merge and process all the data from various Riff sources (e.g. mongoDB, Mattermost, Firebase, etc.). It is a precursor to doing analysis on the NEXT Canada course run. This story is to allocate time for writing a script that does the following. 

** Tasks: **

- [ ] All CSV sources are joined based on participant ID numbers into a single table. Each table row summarizes all known information about a single participant. The table is written out to a file.
-  [ ] Another Python script extracts aggregate features from Mattermost and Mongo databases, and then merges them into the large table that was written out in the previous step. This module is designed to be very easy to extend so that new features can be extracted.
-  [ ] All data containing PII are _not_ extracted to the large table, and all PII is purged from the local system. No PII is ever held in secondary storage, only in the memory of the running process.

** Business Context: **

- It is preferable to build something reusable over doing something very fast that does not create a reusable infrastructure.

**Comment by jaedoucette** [comment]
CSV & SQL extraction are now both functional.

Blocked waiting for review of the CSV feature before making PR for the SQL feature that builds on top of it.
